version: "3.9"

services:
  mover:
    container_name: mover
    image: jacobissa/mover:latest
    volumes:
      - /home/pi/docker/mover/source:/app/source
      - /home/pi/docker/mover/target:/app/target
      - /home/pi/docker/mover/logs:/app/logs
    environment:
      - TZ=Europe/Berlin
      - SLEEP_SCAN=6s
      - SLEEP_MOVE=3s
    restart: unless-stopped